services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    networks:
      - app_network
    ports:
      - "8000:5000"
    depends_on:
      - mongodb
  client:
    build: ./client
    container_name: client
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - app
volumes:
  mongodb_data:
networks:
  app_network:
    driver: bridge
