services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app_network
    ports:
      - "27017:27017"
    volumes:
      - ./:/data/db
    restart: always
  app:
    build: .
    container_name: app
    networks:
      - app_network
    ports:
      - "8000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./:/app
volumes:
  mongodb_data:
networks:
  app_network:
    driver: bridge
